### ISSUE TITLE
Missing application encryption key when installing as instructed

### ISSUE THREAD

**Issue by michaelbiberich** [alexanderglueck/contacts#17]
After installing as instructed in the Readme and starting the HTTP server via `php artisan serve` a `RuntimeError` may be encountered.

> No application encryption key has been specified.

This happens if no `.env` was created or if it is missing (a value for) the key `APP_KEY`.

The following `artisan` command automatically generates a key and adds it to the `.env` (if any):

```
php artisan key:generate
```

It might be a good idea to add this to the list of commands under the section `Install` of the `README.md` (possible before/after running migrations and seeds).

**Comment by alexanderglueck** [comment]
Hey! 
Thanks for pointing this out. Fixed in eee63eee44ecc417cf2193e1259acf2fe53263f6
